### ISSUE TITLE
Invalid timestamp type in --after/--before command line argument

### ISSUE THREAD

**Issue by marthinsen** [10Duke/event-data-reader-cli#6]
When installing the latest version from npm I'm having problems using the --after/--before command line arguments:
```
$ event-data-reader --after 2024-06-26
usage: event-data-reader [-h] [-V] [-k KEY] [-m MAX_EVENT_COUNT] [-a AFTER] [-b BEFORE] [-o OUTPUT]
event-data-reader: error: argument -a/--after: invalid timestamp_type value: '2024-06-26'
```
It does however work when i clone and build the project from source...

**Comment by Jarkko-10Duke** [comment]
That's strange. Version 1.0.0 is the only version ever published, and it has been published from the current HEAD of master, meaning that it should be the same version that you get if you clone the repo and build from master.

I tested this with two different configurations, nodejs 16.20.2 on Ubuntu and nodejs 20.11.0 on Windows, both work for me. Looking into the code, this [Date.parse](https://github.com/10Duke/event-data-reader-cli/blob/d6f49976c5eadd6dfaedb632bce30467245fc940/src/util.ts#L11) is the only place where `-a/--after` and `-b/--before` argument values are parsed as a date, elsewhere they are treated as a string.

This output also looks different from the output of this tool:

```
usage: event-data-reader [-h] [-V] [-k KEY] [-m MAX_EVENT_COUNT] [-a AFTER] [-b BEFORE] [-o OUTPUT]
event-data-reader: error: argument -a/--after: invalid timestamp_type value: '2024-06-26'
```

...or at least I can't think of a way how this could be printed. Do you have a script / alias with the same name `event-data-reader` that wraps the call to this tool?

**Comment by marthinsen** [comment]
I have now completely reinstalled Node and it is working again. I have no idea what I might caused the problem... But thanks for testing it out @Jarkko-10Duke.
